export const memesData = [
  {
    emotionTags: ["angry"],
    isGif: true,
    image: "angry.gif",
    alt: "Ira character in flames",
  },
  {
    emotionTags: ["angry"],
    isGif: true,
    image: "angry2.gif",
    alt: "An angry woman",
  },
  {
    emotionTags: ["angry"],
    isGif: false,
    image: "angry.jpg",
    alt: "A very angry monkey",
  },
  {
    emotionTags: ["confident"],
    isGif: true,
    image: "confident.gif",
  },
  {
    emotionTags: ["confident"],
    isGif: false,
    image: "confident.jpg",
    alt: "A confident man (photo)",
  },
  {
    emotionTags: ["confident"],
    isGif: true,
    image: "confident2.gif",
    alt: "Another confident reaction (gif)",
  },
  {
    emotionTags: ["confused"],
    isGif: true,
    image: "confused.gif",
    alt: "Confused expression (gif)",
  },
  {
    emotionTags: ["confused"],
    isGif: false,
    image: "confused.jpg",
    alt: "Confused expression (photo)",
  },
  {
    emotionTags: ["confused"],
    isGif: true,
    image: "confused2.gif",
    alt: "Confused head tilt (gif)",
  },
  {
    emotionTags: ["confused"],
    isGif: false,
    image: "confused2.jpg",
    alt: "Confused head tilt (photo)",
  },
  {
    emotionTags: ["frustrated", "fed-up"],
    isGif: true,
    image: "fed-up.gif",
    alt: "Fed up reaction (gif)",
  },
  {
    emotionTags: ["frustrated", "fed-up"],
    isGif: false,
    image: "fed-up.jpg",
    alt: "Fed up expression (photo)",
  },
  {
    emotionTags: ["frustrated", "fed-up"],
    isGif: true,
    image: "fed-up2.gif",
    alt: "Very fed up (gif)",
  },
  {
    emotionTags: ["frustrated", "fed-up"],
    isGif: true,
    image: "fed-up3.gif",
    alt: "Extremely fed up (gif)",
  },
  {
    emotionTags: ["impatient"],
    isGif: true,
    image: "impacient.gif",
    alt: "Impatient look (gif)",
  },
  {
    emotionTags: ["impatient"],
    isGif: true,
    image: "impacient2.gif",
    alt: "Tapping foot impatient (gif)",
  },
  {
    emotionTags: ["lazy", "bored"],
    isGif: true,
    image: "lazy.gif",
    alt: "Lazy reaction (gif)",
  },
  {
    emotionTags: ["lazy", "bored"],
    isGif: false,
    image: "lazy.png",
    alt: "Laid-back lazy face (png)",
  },
  {
    emotionTags: ["lazy", "bored"],
    isGif: true,
    image: "lazy2.gif",
    alt: "Very lazy / uninterested (gif)",
  },
  {
    emotionTags: ["sleepy", "tired"],
    isGif: true,
    image: "sleepy.gif",
    alt: "Sleepy yawn (gif)",
  },
  {
    emotionTags: ["sleepy", "tired"],
    isGif: false,
    image: "sleepy.jpg",
    alt: "Drowsy expression (photo)",
  },
  {
    emotionTags: ["sleepy", "tired"],
    isGif: true,
    image: "sleepy2.gif",
    alt: "Falling asleep (gif)",
  },
  {
    emotionTags: ["stressed", "anxious"],
    isGif: true,
    image: "stressed.gif",
    alt: "Stressed out (gif)",
  },
  {
    emotionTags: ["stressed", "anxious"],
    isGif: false,
    image: "stressed.jpg",
    alt: "Stressed expression (photo)",
  },
  {
    emotionTags: ["stressed", "anxious"],
    isGif: true,
    image: "stressed2.gif",
    alt: "Very stressed reaction (gif)",
  },
];
